app:
  name: IngesAI
  host: "0.0.0.0"
  port: 8000

llm:
  provider: "tinyllama"
  model: "tinyllama-1.1b-chat-v1.0"
  temperature: 0.3
  max_new_tokens: 256

embedder:
  provider: "BAAI"
  model: "llm-embedder"
  dimension: 768

storage:
  milvus:
    provider: "milvus"
    cluster: "Pranav_db"
    collection: "IngestAI"